### ISSUE TITLE
chisel crash

### ISSUE THREAD

**Issue by boozzeeboom** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#21]
When u have full inventary and open chisel (from chisel mod) and add some block to chisel GUI and create another block (into full inventory) client will crash with this stacktrace:
`Stacktrace:
	at net.minecraft.inventory.Container.func_75135_a(SourceFile:424)
	at team.chisel.inventory.ContainerChisel.func_82846_b(ContainerChisel.java:108)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
	at team.chisel.inventory.ContainerChisel.func_75144_a(ContainerChisel.java:73)
	at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:199)
	at team.chisel.inventory.ContainerChisel.func_75144_a(ContainerChisel.java:73)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
`

**Comment by yuesha-yc** [comment]
Another TFC Compat has fucked up.
