### ISSUE TITLE
Techguns引发游戏崩溃

### ISSUE THREAD

**Issue by Dirt030** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#23]
# 错误报告
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2020-09-29 10:28:38 CST
Description: Rendering entity in world

java.lang.ArrayIndexOutOfBoundsException: 5
    at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:237)
    at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66)
    at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:78)
    at techguns.client.render.entities.npcs.RenderAttackHelicopter.renderBakedModel(RenderAttackHelicopter.java:153)
    at techguns.client.render.entities.npcs.RenderAttackHelicopter.doRender(RenderAttackHelicopter.java:103)
    at techguns.client.render.entities.npcs.RenderAttackHelicopter.doRender(RenderAttackHelicopter.java:34)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:412)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:392)
    at net.minecraft.client.renderer.RenderGlobal.redirect$renderEntityStatic$zbf000(RenderGlobal.java:3727)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:839)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1800)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1613)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1384)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being rendered --
  Entity Type: techguns:attackhelicopter (techguns.entities.npcs.AttackHelicopter)
  Entity ID: 321
  Entity Name: 武装直升机
  Entity's Exact location: 22.91, 98.90, 15.29
  Entity's Block location: World: (22,98,15), Chunk: (at 6,6,15 in 1,0; contains blocks 16,0,0 to 31,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,ForgeData:{health:100},Attributes:[{Base:0.0d,Name:"techguns.radiationResistance"},{Base:100.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.699999988079071d,Name:"generic.movementSpeed"},{Base:16.0d,Name:"generic.armor"},{Base:5.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:128.0d,Name:"generic.followRange"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,DeathTime:0s,ForgeCaps:{"techguns:shootervalues":{},"techguns:deathtype":{},"flammpfeil.slashblade:mobeffect":{FreezeTimeout:-1L,StunTimeout:-1L},"techguns:genericnpcdata":{}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Motion:[0.0d,0.0d,0.0d],Leashed:0b,UUIDLeast:-8333741062605801558L,Health:100.0f,LeftHanded:1b,Air:300s,OnGround:0b,Dimension:0,Rotation:[-49.21875f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:8286276702846994942L,Pos:[22.91455078125d,98.89501953125d,15.286376953125d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}

-- Renderer details --
  Assigned renderer: techguns.client.render.entities.npcs.RenderAttackHelicopter@304fecb2
  Location: 9.40,11.62,-24.70 - World: (9,11,-25), Chunk: (at 9,0,7 in 0,-2; contains blocks 0,0,-32 to 15,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Rotation: -49.21875
  Delta: 0.9000026

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Dirt030'/297, l='MpServer', x=13.50, y=87.30, z=39.98]]
  Chunk stats: MultiplayerChunkCache: 260, 260
  Level seed: 0
  Level generator: ID 04 - customized, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (140,64,156), Chunk: (at 12,4,12 in 8,9; contains blocks 128,0,144 to 143,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 8244 game time, 8244 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
  Forced entities: 51 total; [EntitySheep['羊'/392, l='MpServer', x=87.48, y=64.00, z=73.15], EntitySheep['羊'/393, l='MpServer', x=80.73, y=64.00, z=76.43], EntitySheep['羊'/394, l='MpServer', x=86.26, y=64.00, z=67.55], EntitySheep['羊'/395, l='MpServer', x=88.59, y=64.00, z=75.60], EntityPlayerSP['Dirt030'/297, l='MpServer', x=13.50, y=87.30, z=39.98], EntitySheep['羊'/399, l='MpServer', x=41.00, y=64.00, z=32.00], EntitySheep['羊'/400, l='MpServer', x=37.42, y=64.00, z=35.58], EntitySheep['羊'/403, l='MpServer', x=47.17, y=64.00, z=27.76], EntitySheep['羊'/404, l='MpServer', x=44.42, y=64.00, z=28.30], EntitySheep['羊'/304, l='MpServer', x=-15.10, y=63.00, z=92.65], EntityItem['item.item.immersiveengineering.seed.hemp'/305, l='MpServer', x=-46.22, y=69.00, z=-13.17], EntitySheep['羊'/307, l='MpServer', x=-17.50, y=63.00, z=89.50], EntitySheep['羊'/308, l='MpServer', x=-18.66, y=63.00, z=93.55], EntitySheep['羊'/309, l='MpServer', x=-20.50, y=63.00, z=90.50], EntitySheep['羊'/310, l='MpServer', x=-14.50, y=63.00, z=64.50], EntitySheep['羊'/312, l='MpServer', x=-23.50, y=64.00, z=31.50], EntitySheep['羊'/313, l='MpServer', x=-21.50, y=64.00, z=29.50], EntitySheep['羊'/314, l='MpServer', x=13.50, y=69.00, z=-20.50], EntitySheep['羊'/315, l='MpServer', x=14.50, y=69.00, z=-23.01], EntitySheep['羊'/316, l='MpServer', x=-14.50, y=63.00, z=62.50], ArmySoldier['军队士兵'/317, l='MpServer', x=25.50, y=64.00, z=16.50], ArmySoldier['军队士兵'/318, l='MpServer', x=6.50, y=66.00, z=6.50], ArmySoldier['军队士兵'/319, l='MpServer', x=10.50, y=66.00, z=6.50], ArmySoldier['军队士兵'/320, l='MpServer', x=8.50, y=66.00, z=11.50], AttackHelicopter['武装直升机'/321, l='MpServer', x=22.91, y=98.90, z=15.29], EntitySheep['羊'/322, l='MpServer', x=-23.50, y=64.00, z=34.50], EntitySheep['羊'/323, l='MpServer', x=-15.98, y=64.00, z=40.09], EntitySheep['羊'/330, l='MpServer', x=-17.50, y=63.00, z=61.50], EntitySheep['羊'/331, l='MpServer', x=-20.52, y=63.00, z=60.79], EntitySheep['羊'/332, l='MpServer', x=18.50, y=70.00, z=-26.50], EntitySheep['羊'/333, l='MpServer', x=17.50, y=69.00, z=-28.50], EntitySheep['羊'/334, l='MpServer', x=17.50, y=69.00, z=-29.50], EntitySheep['羊'/335, l='MpServer', x=18.50, y=70.00, z=-31.50], ArmySoldier['军队士兵'/336, l='MpServer', x=4.50, y=65.00, z=16.50], ArmySoldier['军队士兵'/337, l='MpServer', x=8.50, y=65.00, z=17.50], EntitySheep['羊'/338, l='MpServer', x=9.50, y=68.00, z=-14.50], EntitySheep['羊'/339, l='MpServer', x=15.55, y=69.00, z=-15.51], ArmySoldier['军队士兵'/340, l='MpServer', x=18.53, y=66.00, z=10.38], ArmySoldier['军队士兵'/341, l='MpServer', x=21.50, y=66.00, z=5.50], ArmySoldier['军队士兵'/342, l='MpServer', x=24.50, y=66.00, z=5.50], ArmySoldier['军队士兵'/343, l='MpServer', x=26.50, y=66.00, z=10.50], EntityItem['item.item.immersiveengineering.seed.hemp'/344, l='MpServer', x=36.46, y=63.00, z=103.51], EntityItem['item.item.seeds'/346, l='MpServer', x=33.17, y=63.00, z=102.61], EntityBat['蝙蝠'/349, l='MpServer', x=41.38, y=29.65, z=94.75], EntityPig['猪'/351, l='MpServer', x=-4.31, y=63.00, z=107.17], EntityPig['猪'/352, l='MpServer', x=-5.37, y=63.00, z=106.76], EntityPig['猪'/353, l='MpServer', x=-3.74, y=63.00, z=109.55], EntityPig['猪'/358, l='MpServer', x=-2.50, y=64.00, z=111.50], EntityZombie['僵尸'/359, l='MpServer', x=46.50, y=21.00, z=62.50], ZombieFarmer['僵尸农民'/360, l='MpServer', x=35.59, y=55.00, z=58.02], ZombieFarmer['僵尸农民'/383, l='MpServer', x=45.50, y=39.00, z=116.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_231, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 6839221144 bytes (6522 MB) / 7784628224 bytes (7424 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 61 mods loaded, 61 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                      | Version                  | Source                                            | Signature                                |
       |:------ |:----------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft               | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                     | 9.42                     | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                   | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | smoothfontcore          | mc1.12.2-2.0             | minecraft.jar                                     | None                                     |
       | LCHIJA | ColorUtility            | 1.0.4                    | minecraft.jar                                     | None                                     |
       | LCHIJA | foamfixcore             | 7.7.4                    | minecraft.jar                                     | None                                     |
       | LCHIJA | techguns_core           | 1.12.2-1.0               | minecraft.jar                                     | None                                     |
       | LCHIJA | smoothfont              | mc1.12.2-2.0             | [T]SmoothFont-mc1.12.2-2.0.jar                    | None                                     |
       | LCHIJA | aroma1997core           | 2.0.0.2                  | [D]Aroma1997Core-1.12.2-2.0.0.2.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | baubles                 | 1.5.2                    | [D]Baubles-1.12-1.5.2.jar                         | None                                     |
       | LCHIJA | codechickenlib          | 3.2.2.353                | [D]CodeChickenLib-1.12.2-3.2.2.353-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux            | 2.1.0                    | [D]RedstoneFlux-1.12-2.1.0.6-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | brandonscore            | 2.4.12                   | [D]BrandonsCore-1.12.2-2.4.12.205-universal.jar   | None                                     |
       | LCHIJA | crafttweaker            | 4.1.16                   | [D]CraftTweaker2-1.12-4.1.16.jar                  | None                                     |
       | LCHIJA | ctgui                   | 1.0.0                    | [D]CraftTweaker2-1.12-4.1.16.jar                  | None                                     |
       | LCHIJA | mtlib                   | 3.0.6                    | [D]MTLib-3.0.6.jar                                | None                                     |
       | LCHIJA | modtweaker              | 4.0.17                   | [D]Modtweaker-4.0.17.jar                          | None                                     |
       | LCHIJA | jei                     | 4.15.0.279               | [U]JEI_1.12.2-4.15.0.279.jar                      | None                                     |
       | LCHIJA | crafttweakerjei         | 2.0.2                    | [D]CraftTweaker2-1.12-4.1.16.jar                  | None                                     |
       | LCHIJA | ctm                     | MC1.12.2-0.3.3.22        | [D]CTM-MC1.12.2-0.3.3.22.jar                      | None                                     |
       | LCHIJA | forgelin                | 1.8.3                    | [D]Forgelin-1.8.3.jar                             | None                                     |
       | LCHIJA | mantle                  | 1.12-1.3.3.55            | [D]Mantle-1.12-1.3.3.55.jar                       | None                                     |
       | LCHIJA | betterquesting          | 3.5.299                  | BetterQuesting-3.5.299.jar                        | None                                     |
       | LCHIJA | bq_standard             | 3.4.159                  | [D]StandardExpansion-3.4.159.jar                  | None                                     |
       | LCHIJA | tesla                   | 1.0.63                   | [D]Tesla-1.12.2-1.0.63.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | teslacorelib            | 1.0.15                   | [D]TeslaCoreLib-1.12.2-1.0.15.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | foamfix                 | 0.10.5-1.12.2            | [T]FoamFix-0.10.5-1.12.2.jar                      | None                                     |
       | LCHIJA | vanillafix              | 1.0.10-SNAPSHOT          | [T]VanillaFix-1.0.10-99.jar                       | None                                     |
       | LCHIJA | fw                      | 1.6.0                    | [U]FullscreenWindowed-1.12-1.6.0.jar              | None                                     |
       | LCHIJA | waila                   | 1.8.26                   | [U]Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
       | LCHIJA | inventorytweaks         | 1.63+release.109.220f184 | [U]InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | mapwriter               | 2.8.2                    | [U]MapWriter-1.12.2-2.8.2.jar                     | None                                     |
       | LCHIJA | torohealthmod           | 1.12.2-11                | [U]ToroHealth-1.12.2-11.jar                       | None                                     |
       | LCHIJA | appliedenergistics2     | rv6-stable-6             | Appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | avaritia                | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar            | None                                     |
       | LCHIJA | botania                 | r1.10-361                | Botania_r1.10-361.jar                             | None                                     |
       | LCHIJA | chameleon               | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
       | LCHIJA | chisel                  | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
       | LCHIJA | customnpcs              | 1.12                     | CustomNPCs_1.12.2(30Jan19).jar                    | None                                     |
       | LCHIJA | draconicevolution       | 2.3.22                   | DraconicEvolution-1.12.2-2.3.22.343-universal.jar | None                                     |
       | LCHIJA | tconstruct              | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                  | None                                     |
       | LCHIJA | extrabotany             | 53                       | ExtraBotany-r1.1-53-fix.jar                       | None                                     |
       | LCHIJA | fastleafdecay           | v14                      | FastLeafDecay-v14.jar                             | None                                     |
       | LCHIJA | ic2                     | 2.8.109-ex112            | Industrialcraft-2-2.8.109-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | forestry                | 5.8.2.387                | Forestry_1.12.2-5.8.2.387.jar                     | None                                     |
       | LCHIJA | immersiveengineering    | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | immersivepetroleum      | 1.1.9                    | ImmersivePetroleum-1.12.2-1.1.9.jar               | None                                     |
       | LCHIJA | immersivetech           | 1.3.10                   | ImmersiveTech-1.12-1.3.10.jar                     | None                                     |
       | LCHIJA | industrialforegoing     | 1.12.2-1.12.2            | Industrialforegoing-1.12.2-1.12.12-236.jar        | None                                     |
       | LCHIJA | nbtedit                 | 1.11.2-2.0.2             | NBTEdit-1.12-2.0.2.jar                            | None                                     |
       | LCHIJA | questbook               | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                          | None                                     |
       | LCHIJA | flammpfeil.slashblade   | mc1.12-r24               | SlashBlade-mc1.12-r24.jar                         | None                                     |
       | LCHIJA | slashblade_addon        | 1.1.0                    | SJAP-1.1.0.jar                                    | None                                     |
       | LCHIJA | slashbladetic           | V1.0.8-MC1.12.2          | SlashBladeTic-V1.0.8-MC1.12.2.jar                 | None                                     |
       | LCHIJA | tatw                    | 1.0.1.2.b27              | Tatw-1.12.2-1.0.1.2.b27.jar                       | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | techguns                | 2.0.1.2                  | Techguns-1.12.2-2.0.1.2_1.jar                     | None                                     |
       | LCHIJA | veinminer               | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
       | LCHIJA | veinminermodsupport     | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
       | LCHIJA | phosphor-lighting       | 1.12.2-0.2.4             | [T]Phosphor-1.12.2-0.2.4_build46-universal.jar    | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | teslacorelib_registries | 1.0.15                   | [D]TeslaCoreLib-1.12.2-1.0.15.jar                 | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin ([D]Forgelin-1.8.3.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      CoreMod ([D]Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      CorePlugin ([T]SmoothFont-mc1.12.2-2.0.jar)
                                        bre.smoothfont.asm.Transformer
                                      VanillaFixLoadingPlugin ([T]VanillaFix-1.0.10-99.jar)
                                        
                                      CTMCorePlugin ([D]CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([T]FoamFix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Inventory Tweaks Coremod ([U]InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      ColorUtilityCorePlugin ([U]ColorUtility-universal-1.0.4.jar)
                                        com.Axeryok.ColorUtility.ColorUtilityTransformer
                                      Techguns Core (Techguns-1.12.2-2.0.1.2_1.jar)
                                        techguns.core.TechgunsASMTransformer
                                      PhosphorFMLLoadingPlugin ([T]Phosphor-1.12.2-0.2.4_build46-universal.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.19' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:ON, CRAFTTWEAKER:ON
  Suspected Mods: Techguns (techguns)
  Launched Version: HMCL 3.3.172
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0
```

**Comment by Dirt030** [comment]
目前通过去Curseforge下载了`techguns-1.12.2-2.0.2.0_pre3.2`暂时解决了

**Comment by yuesha-yc** [comment]
我没记错的话整合包里没有TechGuns
